### ISSUE TITLE
AttributeError: 'model' object has no attribute 'restore_check'

### ISSUE THREAD

**Issue by mphirke** [russoale/hmr2.0#1]
When I try to use model.detect(), I get thrown that error. It most likely is because how the restore_check flag is defined an if which might lead it to not be defined if there is no latest checkpoint. 

```# if a checkpoint exists, restore the latest checkpoint.
        if self.checkpoint_manager.latest_checkpoint:
            restore_path = self.config.RESTORE_PATH
            if restore_path is None:
                restore_path = self.checkpoint_manager.latest_checkpoint

            self.restore_check = checkpoint.restore(restore_path).expect_partial()
            print('Checkpoint restored from {}'.format(restore_path)) 
```

When I removed the assertion errors from model.detect(), I could run the model but I got results that are similar to each other and way off from the example COCO images so I am still doing something wrong.

This is the original and the preprocessed inputs: 
![image](https://user-images.githubusercontent.com/22197137/88453298-49a7e900-ce83-11ea-9066-d7f4e580f895.png)

This is the output: 
![image](https://user-images.githubusercontent.com/22197137/88453309-604e4000-ce83-11ea-8bbd-5889251ac730.png)

This is my code: https://colab.research.google.com/drive/1FJIn_kh_yNxU04iBJ5qyWTFp3IyZNESV?usp=sharing

**Comment by russoale** [comment]
Hi @mphirke,

this is because you ran the model without the pretrained model. I just released version 1.0. Follow the instructions in the README.md file.

**Comment by mphirke** [comment]
Thanks a lot. I did as you advised and it works well now. Great work!

**Comment by TheStarkor** [comment]
Thanks for sharing your project @russoale,

I have the same error... I downloaded the pretrained model 

```
# use lsp or lsp_toes
mkdir -p logs/lsp && cd logs/lsp    
curl -L -O https://github.com/russoale/hmr2.0/releases/download/1.0/trained_lsp.zip && unzip trained_lsp.zip
```

However, I have the same error. Here is my error code.

```
(hmr2.0) (base) ho@ina-System-Product-Name:~/Documents/hmr2.0/src$ python trimesh_renderer.py 
/home/ho/Documents/hmr2.0/src/main/model.py:429: SyntaxWarning: "is not" with a literal. Did you mean "!="?
  if len(tf.shape(image)) is not 4:
/home/ho/Documents/hmr2.0/src/main/model.py:469: SyntaxWarning: "is not" with a literal. Did you mean "!="?
  if len(tf.shape(image)) is not 4:
Saving logs to /home/ho/Documents/logs/lsp

Configurations:
BATCH_SIZE                     1
CUSTOM_REGRESSOR_IDX           {0: 'regressor_toes_right.npy', 7: 'regressor_toes_left.npy'}
CUSTOM_REGRESSOR_PATH          /home/ho/Documents/models/regressors
DATASETS                       ['dataset']
DATA_DIR                       /home/ho/Documents/hmr2.0/src/tests/files
DISCRIMINATOR_LEARNING_RATE    0.0001
DISCRIMINATOR_LOSS_WEIGHT      1
DISCRIMINATOR_WEIGHT_DECAY     0.0001
DS_KP2D                        {'lsp': 14, 'cocoplus': 19, 'custom': 21}
DS_KP3D                        {'lsp': 14, 'cocoplus': 14, 'custom': 16}
ENCODER_INPUT_SHAPE            (224, 224, 3)
ENCODER_ONLY                   True
EPOCHS                         55
GENERATOR_2D_LOSS_WEIGHT       60.0
GENERATOR_3D_LOSS_WEIGHT       60.0
GENERATOR_LEARNING_RATE        1e-05
GENERATOR_WEIGHT_DECAY         0.0001
INITIALIZE_CUSTOM_REGRESSOR    False
ITERATIONS                     3
JOINT_TYPE                     cocoplus
LOG_DIR                        /home/ho/Documents/logs/lsp
NUM_CAMERA_PARAMS              3
NUM_JOINTS                     23
NUM_JOINTS_GLOBAL              24
NUM_KP2D                       19
NUM_KP3D                       14
NUM_PARALLEL                   16
NUM_POSE_PARAMS                72
NUM_SHAPE_PARAMS               10
NUM_SMPL_PARAMS                85
NUM_TEST_SAMPLES               1
NUM_TRAINING_SAMPLES           1
NUM_TRAIN_SMPL_SAMPLES         4
NUM_VALIDATION_SAMPLES         1
NUM_VERTICES                   6890
RESTORE_PATH                   None
ROOT_DATA_DIR                  /home/ho/Documents/hmr2.0
ROOT_PROJECT_DIR               /home/ho/Documents/hmr2.0
SCALE_MAX                      1.23
SCALE_MIN                      0.8
SEED                           1
SMPL_DATASETS                  ['smpl']
SMPL_DATA_DIR                  /home/ho/Documents/hmr2.0/src/tests/files
SMPL_MEAN_THETA_PATH           /home/ho/Documents/hmr2.0/models/neutral_smpl_mean_params.h5
SMPL_MODEL_PATH                /home/ho/Documents/hmr2.0/models/neutral_smpl_coco_regressor.pkl
TRANS_MAX                      20
USE_3D                         False
_Config__initialized           True
_Config__instance              <__main__.TrimeshConfig object at 0x7fa9bfe8e130>


building model...

Resizing image to 224
WARNING:tensorflow:From /home/ho/Documents/hmr2.0/src/main/model.py:459: set_learning_phase (from tensorflow.python.keras.backend) is deprecated and will be removed after 2020-10-11.
Instructions for updating:
Simply pass a True/False value to the `training` argument of the `__call__` method of your layer or model.
Traceback (most recent call last):
  File "trimesh_renderer.py", line 123, in <module>
    result = model.detect(input_img)
  File "/home/ho/Documents/hmr2.0/src/main/model.py", line 461, in detect
    if self.restore_check is None:
AttributeError: 'Model' object has no attribute 'restore_check'
```
