### ISSUE TITLE
Facing Value error while running the demo

### ISSUE THREAD

**Issue by palashk1234** [russoale/hmr2.0#12]
Traceback (most recent call last):
  File "/home/palashk/anaconda3/envs/3dbm/lib/python3.9/site-packages/tensorflow/python/framework/ops.py", line 770, in set_shape
    pywrap_tf_session.TF_GraphSetTensorShape_wrapper(
tensorflow.python.framework.errors_impl.InvalidArgumentError: Dimension 1 in both shapes must be equal, but are 112 and 115. Shapes are [1,112,112,64] and [1,115,115,64].

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/palashk/Work/3D_body_reconstruction/hmr2.0-master/src/visualise/demo.py", line 53, in <module>
    model = Model()
  File "/home/palashk/Work/3D_body_reconstruction/hmr2.0-master/src/main/model.py", line 65, in __init__
    self._build_model()
  File "/home/palashk/Work/3D_body_reconstruction/hmr2.0-master/src/main/model.py", line 78, in _build_model
    self.generator.build(input_shape=gen_input)
  File "/home/palashk/anaconda3/envs/3dbm/lib/python3.9/site-packages/tensorflow/python/keras/engine/training.py", line 443, in build
    self.call(x, **kwargs)
  File "/home/palashk/Work/3D_body_reconstruction/hmr2.0-master/src/main/generator.py", line 91, in call
    features = self.resnet50V2(inputs, **kwargs)
  File "/home/palashk/anaconda3/envs/3dbm/lib/python3.9/site-packages/tensorflow/python/keras/engine/base_layer.py", line 1030, in __call__
    outputs = call_fn(inputs, *args, **kwargs)
  File "/home/palashk/anaconda3/envs/3dbm/lib/python3.9/site-packages/tensorflow/python/keras/engine/functional.py", line 420, in call
    return self._run_internal_graph(
  File "/home/palashk/anaconda3/envs/3dbm/lib/python3.9/site-packages/tensorflow/python/keras/engine/functional.py", line 556, in _run_internal_graph
    outputs = node.layer(*args, **kwargs)
  File "/home/palashk/anaconda3/envs/3dbm/lib/python3.9/site-packages/tensorflow/python/keras/engine/base_layer.py", line 1030, in __call__
    outputs = call_fn(inputs, *args, **kwargs)
  File "/home/palashk/anaconda3/envs/3dbm/lib/python3.9/site-packages/tensorflow/python/keras/layers/convolutional.py", line 273, in call
    outputs.set_shape(out_shape)
  File "/home/palashk/anaconda3/envs/3dbm/lib/python3.9/site-packages/tensorflow/python/framework/ops.py", line 777, in set_shape
    raise ValueError(str(e))
ValueError: Dimension 1 in both shapes must be equal, but are 112 and 115. Shapes are [1,112,112,64] and [1,115,115,64].

**Comment by chitara-01** [comment]
Facing the same error. It was not there earlier.

**Comment by palashk1234** [comment]
It's Working.
Thanks

**Comment by palanisamy1169** [comment]
Wow. it is working after a long R&D with other repo. I have one question. is module using OpenPose internally ?
