### ISSUE TITLE
index 4 is out of bounds for axis 1 with size 4

### ISSUE THREAD

**Issue by jiukekun** [russoale/hmr2.0#13]
Hello!
I find this bug when I convert lsp and lsp_ext dataset into tfrecord
Traceback (most recent call last):
  File "lsp_to_tfrecords.py", line 46, in <module>
    lsp_converter = LspConverter()
  File "lsp_to_tfrecords.py", line 17, in __init__
    super().__init__()
  File "/home/hzj/Downloads/hmr2.0-master/datasets_preprocessing/converter/tfrecord_converter.py", line 51, in __init__
    self.check_data()
  File "/home/hzj/Downloads/hmr2.0-master/datasets_preprocessing/converter/tfrecord_converter.py", line 88, in check_data
    d.kps_2d = _reorder(d.kps_2d, d.config.reorder)
  File "/home/hzj/Downloads/hmr2.0-master/datasets_preprocessing/converter/tfrecord_converter.py", line 83, in _reorder
    return **np.concatenate([value, zero], axis=1)[:, reorder]**
IndexError: index 4 is out of bounds for axis 1 with size 4
After deleting the **[:, reorder]**, the bug fixed, dose anybody know why this bug happens and tell me how to fix it in a right way.
Thanks!

**Comment by russoale** [comment]
Hi @jiukekun ,

sorry for the late response. Did you download the original LSP datasets? 
The reorder is used to align all keypoints from different datasets to be in the same order.
So in case of LSP the order is defined as
https://github.com/russoale/hmr2.0/blob/774a7f0267628b0ec67f74f56d66ca86d7782a86/datasets_preprocessing/lsp_to_tfrecords.py#L14-L15
but then converted to this 
https://github.com/russoale/hmr2.0/blob/774a7f0267628b0ec67f74f56d66ca86d7782a86/datasets_preprocessing/converter/tfrecord_converter.py#L354-L355
