### ISSUE TITLE
Question : Problem while launching the demo.py

### ISSUE THREAD

**Issue by bruno-darochac** [russoale/hmr2.0#21]
Hi, your work really interrested me for my Bachelor work, but while I was trying to launch it this error apears : 
```bash
Dimensions must be equal, but are 59 and 61 for '{{node resnet50v2/conv2_block1_out/add}} = AddV2[T=DT_FLOAT](resnet50v2/conv2_block1_0_conv/BiasAdd, resnet50v2/conv2_block1_3_conv/BiasAdd)' with input shapes: [1,59,59,256], [1,61,61,256].

Call arguments received by layer "conv2_block1_out" (type Add):
  • inputs=['tf.Tensor(shape=(1, 59, 59, 256), dtype=float32)', 'tf.Tensor(shape=(1, 61, 61, 256), dtype=float32)']

```
I've follow your README and did all the steps. If you can clarify me it will be really helpful...
Thanks in advance

**Comment by STRUGGLE1999** [comment]
> Hi, your work really interrested me for my Bachelor work, but while I was trying to launch it this error apears :
> 
> ```shell
> Dimensions must be equal, but are 59 and 61 for '{{node resnet50v2/conv2_block1_out/add}} = AddV2[T=DT_FLOAT](resnet50v2/conv2_block1_0_conv/BiasAdd, resnet50v2/conv2_block1_3_conv/BiasAdd)' with input shapes: [1,59,59,256], [1,61,61,256].
> 
> Call arguments received by layer "conv2_block1_out" (type Add):
>   • inputs=['tf.Tensor(shape=(1, 59, 59, 256), dtype=float32)', 'tf.Tensor(shape=(1, 61, 61, 256), dtype=float32)']
> ```
> 
> I've follow your README and did all the steps. If you can clarify me it will be really helpful... Thanks in advance


I have met this problem too,do you solve it?

**Comment by STRUGGLE1999** [comment]
![image](https://user-images.githubusercontent.com/66925708/178186869-11b56b67-ee8f-4d47-ac51-776af37c712c.png)


Could anybody help me? When I launched the demo.py,it broke this error,and I have surfed the Internet for searching the answer,but I still couldn't sovle it?I would appreciate it if somebody help me!

**Comment by bruno-darochac** [comment]
> > Hi, your work really interrested me for my Bachelor work, but while I was trying to launch it this error apears :
> > ```shell
> > Dimensions must be equal, but are 59 and 61 for '{{node resnet50v2/conv2_block1_out/add}} = AddV2[T=DT_FLOAT](resnet50v2/conv2_block1_0_conv/BiasAdd, resnet50v2/conv2_block1_3_conv/BiasAdd)' with input shapes: [1,59,59,256], [1,61,61,256].
> > 
> > Call arguments received by layer "conv2_block1_out" (type Add):
> >   • inputs=['tf.Tensor(shape=(1, 59, 59, 256), dtype=float32)', 'tf.Tensor(shape=(1, 61, 61, 256), dtype=float32)']
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > I've follow your README and did all the steps. If you can clarify me it will be really helpful... Thanks in advance
> 
> I have met this problem too,do you solve it?

I didn't found the problem for the moment sorry :/

**Comment by STRUGGLE1999** [comment]
Ok,thank you anyway!



***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "russoale/hmr2.0"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年7月11日(星期一) 下午5:26
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [russoale/hmr2.0] Question : Problem while launching the demo.py (Issue #21)





   
Hi, your work really interrested me for my Bachelor work, but while I was trying to launch it this error apears :
 Dimensions must be equal, but are 59 and 61 for '{{node resnet50v2/conv2_block1_out/add}} = AddV2[T=DT_FLOAT](resnet50v2/conv2_block1_0_conv/BiasAdd, resnet50v2/conv2_block1_3_conv/BiasAdd)' with input shapes: [1,59,59,256], [1,61,61,256]. Call arguments received by layer "conv2_block1_out" (type Add):   • inputs=['tf.Tensor(shape=(1, 59, 59, 256), dtype=float32)', 'tf.Tensor(shape=(1, 61, 61, 256), dtype=float32)']
 
I've follow your README and did all the steps. If you can clarify me it will be really helpful... Thanks in advance
  
I have met this problem too,do you solve it?
  
I didn't found the problem for the moment sorry :/

**Comment by SimonLisowski** [comment]
> Hi, your work really interrested me for my Bachelor work, but while I was trying to launch it this error apears :
> 
> ```shell
> Dimensions must be equal, but are 59 and 61 for '{{node resnet50v2/conv2_block1_out/add}} = AddV2[T=DT_FLOAT](resnet50v2/conv2_block1_0_conv/BiasAdd, resnet50v2/conv2_block1_3_conv/BiasAdd)' with input shapes: [1,59,59,256], [1,61,61,256].
> 
> Call arguments received by layer "conv2_block1_out" (type Add):
>   • inputs=['tf.Tensor(shape=(1, 59, 59, 256), dtype=float32)', 'tf.Tensor(shape=(1, 61, 61, 256), dtype=float32)']
> ```
> 
> I've follow your README and did all the steps. If you can clarify me it will be really helpful... Thanks in advance

Same problem here unfortunately

**Comment by STRUGGLE1999** [comment]
When I run the demo.py，it broke this error:
How do I solve it?Please help me.

Traceback (most recent call last):
  File "demo.py", line 68, in <module>
    visualize(renderer, original_img, params, vertices, cam, joints)
  File "../visualise/vis_util.py", line 178, in visualize
    img_overlay = renderer(vert_shifted, img=img, bg_color=np.array((255.0, 255.0, 255.0, 1)))
  File "../visualise/trimesh_renderer.py", line 39, in __call__
    image_bytes = scene.save_image(resolution=(w, h), background=bg_color, visible=True)
  File "/home/XiaoLF/anaconda3/envs/hmr/lib/python3.6/site-packages/trimesh/scene/scene.py", line 867, in save_image
    from ..viewer.windowed import render_scene
  File "/home/XiaoLF/anaconda3/envs/hmr/lib/python3.6/site-packages/trimesh/viewer/windowed.py", line 25, in <module>
    import pyglet.gl as gl  # NOQA
  File "/home/XiaoLF/anaconda3/envs/hmr/lib/python3.6/site-packages/pyglet/gl/__init__.py", line 95, in <module>
    from pyglet.gl.gl import *
  File "/home/XiaoLF/anaconda3/envs/hmr/lib/python3.6/site-packages/pyglet/gl/gl.py", line 45, in <module>
    from pyglet.gl.lib import link_GL as _link_function
  File "/home/XiaoLF/anaconda3/envs/hmr/lib/python3.6/site-packages/pyglet/gl/lib.py", line 149, in <module>
    from pyglet.gl.lib_glx import link_GL, link_GLU, link_GLX
  File "/home/XiaoLF/anaconda3/envs/hmr/lib/python3.6/site-packages/pyglet/gl/lib_glx.py", line 46, in <module>
    glu_lib = pyglet.lib.load_library('GLU')
  File "/home/XiaoLF/anaconda3/envs/hmr/lib/python3.6/site-packages/pyglet/lib.py", line 168, in load_library
    raise ImportError('Library "%s" not found.' % names[0])
ImportError: Library "GLU" not found.

**Comment by AphroDatalyst** [comment]
it'll work if you change the version of TensorFlow to 2.3.0

**Comment by XaryWorld** [comment]
> ![image](https://user-images.githubusercontent.com/66925708/178186869-11b56b67-ee8f-4d47-ac51-776af37c712c.png)
> 
> Could anybody help me? When I launched the demo.py,it broke this error,and I have surfed the Internet for searching the answer,but I still couldn't sovle it?I would appreciate it if somebody help me!

I have the same problem. Have you solved it？

**Comment by STRUGGLE1999** [comment]
> > ![image](https://user-images.githubusercontent.com/66925708/178186869-11b56b67-ee8f-4d47-ac51-776af37c712c.png)
> > Could anybody help me? When I launched the demo.py,it broke this error,and I have surfed the Internet for searching the answer,but I still couldn't sovle it?I would appreciate it if somebody help me!
> 
> I have the same problem. Have you solved it？

I have run the demo in this experiment, and I share approach in CSDN, maybe you can visit [https://blog.csdn.net/qq_45257495/article/details/125944038](url)
