### ISSUE TITLE
'restore_check' error when running demo code.

### ISSUE THREAD

**Issue by TheStarkor** [russoale/hmr2.0#4]
Thanks for sharing your project @russoale,

I have the same error #1  when running the demo
```
python trimesh_renderer.py
```

I downloaded the pretrained model
```
# use lsp or lsp_toes
mkdir -p logs/lsp && cd logs/lsp    
curl -L -O https://github.com/russoale/hmr2.0/releases/download/1.0/trained_lsp.zip && unzip trained_lsp.zip
```
However, I have the same error. Here is my error code.

```
(hmr2.0) (base) ho@xxx:~/Documents/hmr2.0/src$ python trimesh_renderer.py 
/home/ho/Documents/hmr2.0/src/main/model.py:429: SyntaxWarning: "is not" with a literal. Did you mean "!="?
  if len(tf.shape(image)) is not 4:
/home/ho/Documents/hmr2.0/src/main/model.py:469: SyntaxWarning: "is not" with a literal. Did you mean "!="?
  if len(tf.shape(image)) is not 4:
Saving logs to /home/ho/Documents/logs/lsp

Configurations:
BATCH_SIZE                     1
CUSTOM_REGRESSOR_IDX           {0: 'regressor_toes_right.npy', 7: 'regressor_toes_left.npy'}
CUSTOM_REGRESSOR_PATH          /home/ho/Documents/models/regressors
DATASETS                       ['dataset']
DATA_DIR                       /home/ho/Documents/hmr2.0/src/tests/files
DISCRIMINATOR_LEARNING_RATE    0.0001
DISCRIMINATOR_LOSS_WEIGHT      1
DISCRIMINATOR_WEIGHT_DECAY     0.0001
DS_KP2D                        {'lsp': 14, 'cocoplus': 19, 'custom': 21}
DS_KP3D                        {'lsp': 14, 'cocoplus': 14, 'custom': 16}
ENCODER_INPUT_SHAPE            (224, 224, 3)
ENCODER_ONLY                   True
EPOCHS                         55
GENERATOR_2D_LOSS_WEIGHT       60.0
GENERATOR_3D_LOSS_WEIGHT       60.0
GENERATOR_LEARNING_RATE        1e-05
GENERATOR_WEIGHT_DECAY         0.0001
INITIALIZE_CUSTOM_REGRESSOR    False
ITERATIONS                     3
JOINT_TYPE                     cocoplus
LOG_DIR                        /home/ho/Documents/logs/lsp
NUM_CAMERA_PARAMS              3
NUM_JOINTS                     23
NUM_JOINTS_GLOBAL              24
NUM_KP2D                       19
NUM_KP3D                       14
NUM_PARALLEL                   16
NUM_POSE_PARAMS                72
NUM_SHAPE_PARAMS               10
NUM_SMPL_PARAMS                85
NUM_TEST_SAMPLES               1
NUM_TRAINING_SAMPLES           1
NUM_TRAIN_SMPL_SAMPLES         4
NUM_VALIDATION_SAMPLES         1
NUM_VERTICES                   6890
RESTORE_PATH                   None
ROOT_DATA_DIR                  /home/ho/Documents/hmr2.0
ROOT_PROJECT_DIR               /home/ho/Documents/hmr2.0
SCALE_MAX                      1.23
SCALE_MIN                      0.8
SEED                           1
SMPL_DATASETS                  ['smpl']
SMPL_DATA_DIR                  /home/ho/Documents/hmr2.0/src/tests/files
SMPL_MEAN_THETA_PATH           /home/ho/Documents/hmr2.0/models/neutral_smpl_mean_params.h5
SMPL_MODEL_PATH                /home/ho/Documents/hmr2.0/models/neutral_smpl_coco_regressor.pkl
TRANS_MAX                      20
USE_3D                         False
_Config__initialized           True
_Config__instance              <__main__.TrimeshConfig object at 0x7fa9bfe8e130>


building model...

Resizing image to 224
WARNING:tensorflow:From /home/ho/Documents/hmr2.0/src/main/model.py:459: set_learning_phase (from tensorflow.python.keras.backend) is deprecated and will be removed after 2020-10-11.
Instructions for updating:
Simply pass a True/False value to the `training` argument of the `__call__` method of your layer or model.
Traceback (most recent call last):
  File "trimesh_renderer.py", line 123, in <module>
    result = model.detect(input_img)
  File "/home/ho/Documents/hmr2.0/src/main/model.py", line 461, in detect
    if self.restore_check is None:
AttributeError: 'Model' object has no attribute 'restore_check'
```

**Comment by mphirke** [comment]
I was the one who originally opened the issue you linked, but it is solved. I could be wrong but it seems like you're using lsp_toes configuration file with lsp. If you have custom regressors linked in the file, you need the right toe and left toe npy regressors which needed to be downloaded using the other option (lsp_toes). 

Can you post your Config class? 

You can check this notebook for reference if you want. I had used it a few months back to try  out hmr2.0 on colb : https://colab.research.google.com/drive/1o8sCmbPY-CxL5k79em1lkuumrVD4Ea8F?usp=sharing

**Comment by TheStarkor** [comment]
Thanks for answering this and sharing your colab notebook @mphirke!

As you suggested config was the problem, I fix LOG_DIR of src/main/config.py but there is another config class in the trimesh_renderer.py, so it did not work! Even though there is a new error in the `visualize()` function in the `src/notebooks/vis_util.py`, I get the prediction result of the model!
